{% set name = "posebusters" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/posebusters-{{ version }}.tar.gz
  sha256: 930f93331005e33d31b7dc93bd958d3241e75f6416df363a51497499ffc28c7b

build:
  entry_points:
    - bust = posebusters.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - rdkit >=2024.9
    - pandas
    - numpy
    - pyyaml

test:
  imports:
    - posebusters
  commands:
    - pip check
    - bust --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'PoseBusters: Plausibility checks for generated molecule poses.'
  home: https://posebusters.readthedocs.io/
  dev_url: https://github.com/maabuu/posebusters/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
