{% set name = "posebusters" %}
{% set version = "0.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/posebusters-{{ version }}.tar.gz
  sha256: 6de4aab09f0dc72388562322311460f62c199fe945a0d045a2bb1f9fc19bf582

build:
  entry_points:
    - bust = posebusters.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7
    - rdkit >=2020.09
    - pandas
    - numpy
    - pyyaml

test:
  imports:
    - posebusters
  commands:
    - pip check
    - bust --help
  requires:
    - pip

about:
  summary: 'PoseBusters: Plausibility checks for generated molecule poses.'
  home: https://posebusters.readthedocs.io/
  dev_url: https://github.com/maabuu/posebusters/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
